name: vector_path
description: Vector geometry library for Dart to manipulate vector path consisting of lines, bezier quadratic curve, bezier cubic curve and arc
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  vector_math: ^2.1.4
  fraction: ^5.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
